export const DEFAULT_CARDS = [
	"(-10) Highly addictive ↔ Mildly addictive (+10)",
	'(-10) Cold ↔ Hot (+10)',
	"(-10) Weird ↔ Normal (+10)",
	"(-10) Colorful ↔ Colorless (+10)",
	"(-10) High calorie ↔ Low calorie (+10)",
	"(-10) Feels good ↔ Feels bad (+10)",
	"(-10) Essential ↔ Inessential (+10)",
	"(-10) Expensive ↔ Cheap (+10)",
	"(-10) Overrated weapon ↔ Underrated weapon (+10)",
	"(-10) Common ↔ Rare (+10)",
	"(-10) Hard subject ↔ Easy subject (+10)",
	"(-10) Famous ↔ Unknown (+10)",
	"(-10) Easy to use ↔ Difficult to use (+10)",
	"(-10) Clean ↔ Dirty (+10)",
	"(-10) Requires skill ↔ Requires luck (+10)",
	"(-10) Flavorful ↔ Flavorless (+10)",
	"(-10) Fascinating topic ↔ Boring topic (+10)",
	"(-10) Hipster ↔ Basic (+10)",
	"(-10) Safe job ↔ Dangerous job (+10)",
	"(-10) Sci+Fi ↔ Fantasy (+10)",
	"(-10) Formal ↔ Casual (+10)",
	"(-10) Overpaid ↔ Underpaid (+10)",
	"(-10) Wet ↔ Dry (+10)",
	"(-10) Overrated skill ↔ Underrated skill (+10)",
	"(-10) Encouraged ↔ Forbidden (+10)",
	"(-10) Happy song ↔ Sad song (+10)",
	"(-10) Durable ↔ Fragile (+10)",
	"(-10) Dork ↔ Geek (+10)",
	"(-10) Evil ↔ Good (+10)",
	"(-10) Best day of the year ↔ Worst day of the year (+10)",
	"(-10) Good habit ↔ Bad habit (+10)",
	"(-10) Dog person ↔ Cat person (+10)",
	"(-10) Openly love ↔ Guilty pleasure (+10)",
	"(-10) Talented ↔ Untalented (+10)",
	"(-10) Light ↔ Dark (+10)",
	"(-10) Overrated actor  ↔ Underrated actor (+10)",
	"(-10) Easy to find ↔ Hard to find (+10)",
	"(-10) Beautiful man ↔ Ugly man (+10)",
	"(-10) Easy to remember ↔ Hard to remember (+10)",
	"(-10) Highbrow ↔ Lowbrow (+10)",
	"(-10) Healthy ↔ Unhealthy (+10)",
	"(-10) Good man ↔ Bad man (+10)",
	"(-10) Historically irrelevant ↔ Historically important (+10)",
	"(-10) Hairy ↔ Hairless (+10)",
	"(-10) Flexible ↔ Inflexible (+10)",
	"(-10) Exotic pet ↔ Normal pet (+10)",
	"(-10) Extrovert ↔ Introvert (+10)",
	"(-10) Movie was better ↔ Book was better (+10)",
	"(-10) Good movie ↔ Bad movie (+10)",
	"(-10) Beautiful ↔ Ugly (+10)",
	"(-10) Happens suddenly ↔ Happens slowly (+10)",
	"(-10) Career ↔ Job (+10)",
	"(-10) Hated ↔ Loved (+10)",
	"(-10) The Dark Side of the Force ↔ The Light Side of the Force (+10)",
	"(-10) Good pizza topping ↔ Bad pizza topping (+10)",
	"(-10) Utopia ↔ Dystopia (+10)",
	"(-10) Immature person ↔ Mature person (+10)",
	"(-10) Overrated thing to own ↔ Underrated thing to own (+10)",
	"(-10) Nice person ↔ Mean person (+10)",
	"(-10) Adventure movie ↔ Action movie (+10)",
	"(-10) Good ↔ Bad (+10)",
	"(-10) Sexy ↔ Unsexy  (+10)",
	"(-10) Wired ↔ Tired (+10)",
	"(-10) Good actor ↔ Bad actor (+10)",
	"(-10) Believable ↔ Unbelievable (+10)",
	"(-10) Classy ↔ Trashy (+10)",
	"(-10) Permanent ↔ Temporary (+10)",
	"(-10) Doesn't look like a person ↔ Looks like a person (+10)",
	"(-10) Tastes good ↔ Tastes bad (+10)",
	"(-10) Game ↔ Sport (+10)",
	"(-10) Cool ↔ Uncool (+10)",
	"(-10) Greatest living person ↔ Worst living person (+10)",
	"(-10) Overrated ↔ Underrated (+10)",
	"(-10) Clean food ↔ Messy food (+10)",
	"(-10) Ethical ↔ Unethical (+10)",
	"(-10) Good gift ↔ Bad gift (+10)",
	"(-10) Fashionable ↔ Unfashionable (+10)",
	"(-10) Terrorist ↔ Freedom fighter (+10)",
	"(-10) Forgiveable ↔ Unforgiveable (+10)",
	"(-10) Harmful ↔ Harmless (+10)",
	"(-10) Hygienic ↔ Unhygienic (+10)",
	"(-10) Good music ↔ Bad music (+10)",
	"(-10) Useful ↔ Useless (+10)",
	"(-10) Art ↔ Movie that Godzilla would ruin (+10)",
	"(-10) Important ↔ Unimportant (+10)",
	"(-10) Hard to spell ↔ Easy to spell (+10)",
	"(-10) Virtue ↔ Vice (+10)",
	"(-10) Overrated musician ↔ Underrated musician (+10)",
	"(-10) Popular activity ↔ Unpopular activity (+10)",
	"(-10) Whole ↔ Divided (+10)",
	"(-10) Reliable ↔ Unreliable (+10)",
	"(-10) Hard to kill ↔ Easy to kill (+10)",
	"(-10) Stable ↔ Unstable (+10)",
	"(-10) Pointy animal ↔ Round animal (+10)",
	"(-10) Good TV show ↔ Bad TV show (+10)",
	"(-10) Traditionally feminine ↔ Traditionally masculine (+10)",
	"(-10) Useful body part ↔ Useless body part (+10)",
	"(-10) Classic ↔ Fad (+10)",
	"(-10) Brilliant ↔ Stupid (+10)",
	"(-10) Strong ↔ Weak (+10)",
	"(-10) Useful invention ↔ Useless invention (+10)",
	"(-10) Conservative ↔ Liberal (+10)",
	"(-10) Popular ↔ Unpopular (+10)",
	"(-10) Enemy ↔ Friend (+10)",
	"(-10) Exciting ↔ Boring (+10)",
	"(-10) Smelly in a good way ↔ Smelly in a bad way (+10)",
	"(-10) Hero ↔ Villain (+10)",
	"(-10) Overrated thing to do ↔ Underrated thing to do (+10)",
	"(-10) Useful in an emergency ↔ Useless in an emergency (+10)",
	"(-10) For adults ↔ For kids (+10)",
	"(-10) Hard to do ↔ Easy to do (+10)",
	"(-10) Priceless ↔ Worthless (+10)",
	"(-10) Nurture ↔ Nature (+10)",
	"(-10) Weird greeting ↔ Normal greeting (+10)",
	"(-10) Cat name ↔ Dog name (+10)",
	"(-10) Infinite ↔ Limited (+10)",
	"(-10) Formal event ↔ Casual event (+10)",
	"(-10) Good investment ↔ Bad investment (+10)",
	"(-10) Heavy topic ↔ Small talk (+10)",
	"(-10) Spicy ↔ Mild (+10)",
	"(-10) Art ↔ Not art (+10)",
	"(-10) Prohibited ↔ Illegal (+10)",
	"(-10) Elitist ↔ Popular (+10)",
	"(-10) In control ↔ Out of control (+10)",
	"(-10) Loud ↔ Quiet (+10)",
	"(-10) Public knowledge ↔ Secret (+10)",
	"(-10) Too big ↔ Too small (+10)",
	"(-10) Long ↔ Short (+10)",
	"(-10) Best year in history ↔ Worst year in history (+10)",
	"(-10) Well known fact ↔ Little known fact (+10)",
	"(-10) Mobile ↔ Stationary (+10)",
	"(-10) Global issue ↔ Local issue (+10)",
	"(-10) Skill ↔ Talent (+10)",
	"(-10) Best era to time travel ↔ Worst era to time travel (+10)",
	"(-10) The best ↔ The worst (+10)",
	"(-10) Large number ↔ Small number (+10)",
	"(-10) False ↔ True (+10)",
	"(-10) Avant garde ↔ Old fashioned (+10)",
	"(-10) Beautiful word ↔ Ugly word (+10)",
	"(-10) Tiny ↔ Small (+10)",
	"(-10) Natural ↔ Unnatural (+10)",
	"(-10) Phony person ↔ Genuine person (+10)",
	"(-10) Original ↔ Derivative (+10)",
	"(-10) Sexy color ↔ Unsexy color (+10)",
	"(-10) Benefits everyone ↔ Benefits you (+10)",
	"(-10) Powerful ↔ Powerless (+10)",
	"(-10) Vapes ↔ Doesn’t vape (+10)",
	"(-10) Vegetable ↔ Fruit (+10)",
	"(-10) Pseudoscience ↔ Science (+10)",
	"(-10) Serious topic ↔ Funny topic (+10)",
	"(-10) Firm ↔ Limp (+10)",
	"(-10) News ↔ Gossip (+10)",
	"(-10) Easy to sit on ↔ Hard to sit on (+10)",
	"(-10) Too much ↔ Not enough (+10)",
	"(-10) Vertical ↔ Horizontal (+10)",
	"(-10) Scented ↔ Unscented (+10)",
	"(-10) Not huggable ↔ Huggable (+10)",
	"(-10) Homogenous ↔ Heterogeneous (+10)",
	"(-10) Exclusive ↔ Inclusive (+10)",
	"(-10) Good dog breed ↔ Bad dog breed (+10)",
	"(-10) Commerce ↔ Art (+10)",
	"(-10) Pop icon ↔ One hit wonder (+10)",
	"(-10) Good advice ↔ Bad advice (+10)",
	"(-10) Good candy ↔ Bad candy (licorice) (+10)",
	"(-10) Radical ↔ Traditional (+10)",
	"(-10) Good mouthfeel ↔ Bad mouthfeel (+10)",
	"(-10) Legal ↔ Illegal (+10)",
	"(-10) Shallow thought ↔ Deep thought (+10)",
	"(-10) Good school ↔ Bad school (+10)",
	"(-10) Always on time ↔ Never on time (+10)",
	"(-10) Will live to 100 ↔ Won't live to 100 (+10)",
	"(-10) Good Disney character ↔ Bad Disney character (+10)",
	"(-10) Good president ↔ Bad president (+10)",
	"(-10) Strange ↔ Weird (+10)",
	"(-10) Infamous ↔ Famous (+10)",
	"(-10) Most powerful god ↔ Least powerful god (+10)",
	"(-10) Fun person ↔ Boring person (+10)",
	"(-10) Overrated book ↔ Underrated book (+10)",
	"(-10) Best chore ↔ Worst chore (+10)",
	"(-10) Overpopulated species ↔ Endangered species (+10)",
	"(-10) Green ↔ Blue (+10)",
	"(-10) Terrifying ↔ Thrilling (+10)",
	"(-10) Unexpected ↔ Expected (+10)",
	"(-10) Person who’d beat you up ↔ Person you could beat up (+10)",
	"(-10) Overrated game ↔ Underrated game (+10)",
	"(-10) You don't want your parents to watch you do it ↔ You want your parents to watch you do it (+10)",
	"(-10) Evil people ↔ Good people (+10)",
	"(-10) jock ↔ nerd  (+10)",
]